// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: dashboards.sql

package store

import (
	"context"
)

const createdashboard = `-- name: Createdashboard :one
INSERT INTO dashboards (
    session_id,
    stop_id
) VALUES (
    ?, ?
)
RETURNING id, session_id, stop_id, created_at
`

type CreatedashboardParams struct {
	SessionID string
	StopID    int64
}

func (q *Queries) Createdashboard(ctx context.Context, arg CreatedashboardParams) (Dashboard, error) {
	row := q.db.QueryRowContext(ctx, createdashboard, arg.SessionID, arg.StopID)
	var i Dashboard
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.StopID,
		&i.CreatedAt,
	)
	return i, err
}
