// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
)

type Dashboard struct {
	ID        int64
	SessionID string
	StopID    int64
	CreatedAt sql.NullTime
}

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    sql.NullTime
}

type Line struct {
	ID          int64
	Code        string
	Destination string
	Direction   int64
	CreatedAt   sql.NullTime
	Mode        sql.NullString
	Color       sql.NullString
}

type Session struct {
	ID        string
	CreatedAt sql.NullTime
	Locale    string
	Theme     string
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}

type Stop struct {
	ID        int64
	Code      string
	Geo       string
	Name      string
	CreatedAt sql.NullTime
}

type StopsByLine struct {
	ID        int64
	StopID    int64
	LineID    int64
	Order     int64
	CreatedAt sql.NullTime
}
