// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package store

import (
	"database/sql"
)

type GooseDbVersion struct {
	ID        int64
	VersionID int64
	IsApplied int64
	Tstamp    sql.NullTime
}

type Session struct {
	ID        string
	CreatedAt sql.NullTime
}

type SqliteSequence struct {
	Name interface{}
	Seq  interface{}
}
